#include <iostream>
#include <cmath>
#include <unordered_map>
#include <chrono>
#include <thread>
#include <bpf/libbpf.h>
#include <zmq.hpp>
#include "sentinel.h"
#include "sentinel.skel.h" // Generated by bpftool gen skeleton

// Global state for calculating entropy over a sliding window
std::unordered_map<__u32, int> syscall_freq;
int total_events = 0;

double calculate_shannon_entropy() {
    double entropy = 0.0;
    if (total_events == 0) return 0.0;
    
    for (const auto& pair : syscall_freq) {
        double p_x = static_cast<double>(pair.second) / total_events;
        if (p_x > 0) {
            entropy -= p_x * std::log2(p_x);
        }
    }
    return entropy;
}

int handle_bpf_event(void *ctx, void *data, size_t data_sz) {
    const struct event_t *e = static_cast<const struct event_t *>(data);
    syscall_freq[e->syscall_id]++;
    total_events++;
    return 0;
}

int main() {
    // 1. Initialize ZeroMQ Publisher
    zmq::context_t context(1);
    zmq::socket_t publisher(context, zmq::socket_type::pub);
    publisher.bind("tcp://127.0.0.1:5555"); // Topic: telemetry_raw

    // 2. Load BPF Skeleton
    struct sentinel_bpf *skel = sentinel_bpf__open_and_load();
    if (!skel) {
        std::cerr << "Failed to open and load BPF skeleton\n";
        return 1;
    }
    sentinel_bpf__attach(skel);

    // 3. Setup Ring Buffer
    struct ring_buffer *rb = ring_buffer__new(bpf_map__fd(skel->maps.rb), handle_bpf_event, NULL, NULL);
    if (!rb) {
        std::cerr << "Failed to create ring buffer\n";
        return 1;
    }

    std::cout << "[Layer 0] Sentinel Active. Hooked into kernel tracepoints.\n";

    // 4. Main Event Loop
    auto last_pub_time = std::chrono::steady_clock::now();
    while (true) {
        ring_buffer__poll(rb, 100 /* timeout ms */);

        auto now = std::chrono::steady_clock::now();
        if (std::chrono::duration_cast<std::chrono::milliseconds>(now - last_pub_time).count() >= 1000) {
            double entropy = calculate_shannon_entropy();
            
            // Format JSON payload
            std::string payload = R"({"timestamp": )" + std::to_string(std::time(nullptr)) + 
                                  R"(, "entropy_score": )" + std::to_string(entropy) + "}";
            
            zmq::message_t message(payload.size());
            memcpy(message.data(), payload.data(), payload.size());
            
            // Broadcast on telemetry_raw topic
            publisher.send(zmq::str_buffer("telemetry_raw"), zmq::send_flags::sndmore);
            publisher.send(message, zmq::send_flags::none);

            // Reset window
            syscall_freq.clear();
            total_events = 0;
            last_pub_time = now;
        }
    }
    ring_buffer__free(rb);
    sentinel_bpf__destroy(skel);
    return 0;
}
